// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/urlshortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // The long URL to shorten
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                                     // The shortened URL
	AlreadyExists bool                   `protobuf:"varint,2,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"` // True if URL already existed in the system
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ShortenURLResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // The token/ID from shortened URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // The original long URL
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`      // True if URL has been marked as deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetOriginalURLResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ShortenBatchRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*ShortenBatchRequest_BatchItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest) Reset() {
	*x = ShortenBatchRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest) ProtoMessage() {}

func (x *ShortenBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenBatchRequest) GetItems() []*ShortenBatchRequest_BatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ShortenBatchResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Results       []*ShortenBatchResponse_BatchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse) Reset() {
	*x = ShortenBatchResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse) ProtoMessage() {}

func (x *ShortenBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenBatchResponse) GetResults() []*ShortenBatchResponse_BatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{6}
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Urls          []*GetUserURLsResponse_UserURL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserURLsResponse) GetUrls() []*GetUserURLsResponse_UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []string               `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"` // List of tokens to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserURLsRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{9}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{10}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseOk    bool                   `protobuf:"varint,1,opt,name=database_ok,json=databaseOk,proto3" json:"database_ok,omitempty"` // True if database is accessible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetDatabaseOk() bool {
	if x != nil {
		return x.DatabaseOk
	}
	return false
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{12}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`   // Total number of URLs in the system
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"` // Total number of unique users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

type ShortenBatchRequest_BatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Client-provided ID to match request/response
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`       // The long URL to shorten
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchRequest_BatchItem) Reset() {
	*x = ShortenBatchRequest_BatchItem{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchRequest_BatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequest_BatchItem) ProtoMessage() {}

func (x *ShortenBatchRequest_BatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequest_BatchItem.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequest_BatchItem) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ShortenBatchRequest_BatchItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchRequest_BatchItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchResponse_BatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Matches the correlation_id from request
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`                // The shortened URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenBatchResponse_BatchResult) Reset() {
	*x = ShortenBatchResponse_BatchResult{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenBatchResponse_BatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponse_BatchResult) ProtoMessage() {}

func (x *ShortenBatchResponse_BatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponse_BatchResult.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponse_BatchResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ShortenBatchResponse_BatchResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchResponse_BatchResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetUserURLsResponse_UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`          // The shortened URL
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // The original URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse_UserURL) Reset() {
	*x = GetUserURLsResponse_UserURL{}
	mi := &file_internal_proto_urlshortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse_UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse_UserURL) ProtoMessage() {}

func (x *GetUserURLsResponse_UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_urlshortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse_UserURL.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse_UserURL) Descriptor() ([]byte, []int) {
	return file_internal_proto_urlshortener_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetUserURLsResponse_UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *GetUserURLsResponse_UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_internal_proto_urlshortener_proto protoreflect.FileDescriptor

const file_internal_proto_urlshortener_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/urlshortener.proto\x12\furlshortener\"%\n" +
	"\x11ShortenURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"S\n" +
	"\x12ShortenURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12%\n" +
	"\x0ealready_exists\x18\x02 \x01(\bR\ralreadyExists\"-\n" +
	"\x15GetOriginalURLRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"Z\n" +
	"\x16GetOriginalURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\"\xaf\x01\n" +
	"\x13ShortenBatchRequest\x12A\n" +
	"\x05items\x18\x01 \x03(\v2+.urlshortener.ShortenBatchRequest.BatchItemR\x05items\x1aU\n" +
	"\tBatchItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\xb3\x01\n" +
	"\x14ShortenBatchResponse\x12H\n" +
	"\aresults\x18\x01 \x03(\v2..urlshortener.ShortenBatchResponse.BatchResultR\aresults\x1aQ\n" +
	"\vBatchResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"\x14\n" +
	"\x12GetUserURLsRequest\"\x9f\x01\n" +
	"\x13GetUserURLsResponse\x12=\n" +
	"\x04urls\x18\x01 \x03(\v2).urlshortener.GetUserURLsResponse.UserURLR\x04urls\x1aI\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"/\n" +
	"\x15DeleteUserURLsRequest\x12\x16\n" +
	"\x06tokens\x18\x01 \x03(\tR\x06tokens\"\x18\n" +
	"\x16DeleteUserURLsResponse\"\r\n" +
	"\vPingRequest\"/\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vdatabase_ok\x18\x01 \x01(\bR\n" +
	"databaseOk\"\x11\n" +
	"\x0fGetStatsRequest\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\xd5\x04\n" +
	"\x13URLShortenerService\x12O\n" +
	"\n" +
	"ShortenURL\x12\x1f.urlshortener.ShortenURLRequest\x1a .urlshortener.ShortenURLResponse\x12[\n" +
	"\x0eGetOriginalURL\x12#.urlshortener.GetOriginalURLRequest\x1a$.urlshortener.GetOriginalURLResponse\x12U\n" +
	"\fShortenBatch\x12!.urlshortener.ShortenBatchRequest\x1a\".urlshortener.ShortenBatchResponse\x12R\n" +
	"\vGetUserURLs\x12 .urlshortener.GetUserURLsRequest\x1a!.urlshortener.GetUserURLsResponse\x12[\n" +
	"\x0eDeleteUserURLs\x12#.urlshortener.DeleteUserURLsRequest\x1a$.urlshortener.DeleteUserURLsResponse\x12=\n" +
	"\x04Ping\x12\x19.urlshortener.PingRequest\x1a\x1a.urlshortener.PingResponse\x12I\n" +
	"\bGetStats\x12\x1d.urlshortener.GetStatsRequest\x1a\x1e.urlshortener.GetStatsResponseB1Z/github.com/pcristin/urlshortener/internal/protob\x06proto3"

var (
	file_internal_proto_urlshortener_proto_rawDescOnce sync.Once
	file_internal_proto_urlshortener_proto_rawDescData []byte
)

func file_internal_proto_urlshortener_proto_rawDescGZIP() []byte {
	file_internal_proto_urlshortener_proto_rawDescOnce.Do(func() {
		file_internal_proto_urlshortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_urlshortener_proto_rawDesc), len(file_internal_proto_urlshortener_proto_rawDesc)))
	})
	return file_internal_proto_urlshortener_proto_rawDescData
}

var file_internal_proto_urlshortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_proto_urlshortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),                // 0: urlshortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),               // 1: urlshortener.ShortenURLResponse
	(*GetOriginalURLRequest)(nil),            // 2: urlshortener.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil),           // 3: urlshortener.GetOriginalURLResponse
	(*ShortenBatchRequest)(nil),              // 4: urlshortener.ShortenBatchRequest
	(*ShortenBatchResponse)(nil),             // 5: urlshortener.ShortenBatchResponse
	(*GetUserURLsRequest)(nil),               // 6: urlshortener.GetUserURLsRequest
	(*GetUserURLsResponse)(nil),              // 7: urlshortener.GetUserURLsResponse
	(*DeleteUserURLsRequest)(nil),            // 8: urlshortener.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),           // 9: urlshortener.DeleteUserURLsResponse
	(*PingRequest)(nil),                      // 10: urlshortener.PingRequest
	(*PingResponse)(nil),                     // 11: urlshortener.PingResponse
	(*GetStatsRequest)(nil),                  // 12: urlshortener.GetStatsRequest
	(*GetStatsResponse)(nil),                 // 13: urlshortener.GetStatsResponse
	(*ShortenBatchRequest_BatchItem)(nil),    // 14: urlshortener.ShortenBatchRequest.BatchItem
	(*ShortenBatchResponse_BatchResult)(nil), // 15: urlshortener.ShortenBatchResponse.BatchResult
	(*GetUserURLsResponse_UserURL)(nil),      // 16: urlshortener.GetUserURLsResponse.UserURL
}
var file_internal_proto_urlshortener_proto_depIdxs = []int32{
	14, // 0: urlshortener.ShortenBatchRequest.items:type_name -> urlshortener.ShortenBatchRequest.BatchItem
	15, // 1: urlshortener.ShortenBatchResponse.results:type_name -> urlshortener.ShortenBatchResponse.BatchResult
	16, // 2: urlshortener.GetUserURLsResponse.urls:type_name -> urlshortener.GetUserURLsResponse.UserURL
	0,  // 3: urlshortener.URLShortenerService.ShortenURL:input_type -> urlshortener.ShortenURLRequest
	2,  // 4: urlshortener.URLShortenerService.GetOriginalURL:input_type -> urlshortener.GetOriginalURLRequest
	4,  // 5: urlshortener.URLShortenerService.ShortenBatch:input_type -> urlshortener.ShortenBatchRequest
	6,  // 6: urlshortener.URLShortenerService.GetUserURLs:input_type -> urlshortener.GetUserURLsRequest
	8,  // 7: urlshortener.URLShortenerService.DeleteUserURLs:input_type -> urlshortener.DeleteUserURLsRequest
	10, // 8: urlshortener.URLShortenerService.Ping:input_type -> urlshortener.PingRequest
	12, // 9: urlshortener.URLShortenerService.GetStats:input_type -> urlshortener.GetStatsRequest
	1,  // 10: urlshortener.URLShortenerService.ShortenURL:output_type -> urlshortener.ShortenURLResponse
	3,  // 11: urlshortener.URLShortenerService.GetOriginalURL:output_type -> urlshortener.GetOriginalURLResponse
	5,  // 12: urlshortener.URLShortenerService.ShortenBatch:output_type -> urlshortener.ShortenBatchResponse
	7,  // 13: urlshortener.URLShortenerService.GetUserURLs:output_type -> urlshortener.GetUserURLsResponse
	9,  // 14: urlshortener.URLShortenerService.DeleteUserURLs:output_type -> urlshortener.DeleteUserURLsResponse
	11, // 15: urlshortener.URLShortenerService.Ping:output_type -> urlshortener.PingResponse
	13, // 16: urlshortener.URLShortenerService.GetStats:output_type -> urlshortener.GetStatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_urlshortener_proto_init() }
func file_internal_proto_urlshortener_proto_init() {
	if File_internal_proto_urlshortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_urlshortener_proto_rawDesc), len(file_internal_proto_urlshortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_urlshortener_proto_goTypes,
		DependencyIndexes: file_internal_proto_urlshortener_proto_depIdxs,
		MessageInfos:      file_internal_proto_urlshortener_proto_msgTypes,
	}.Build()
	File_internal_proto_urlshortener_proto = out.File
	file_internal_proto_urlshortener_proto_goTypes = nil
	file_internal_proto_urlshortener_proto_depIdxs = nil
}
